### ISSUE TITLE
Does not handle file paths which require URL encoding

### ISSUE THREAD

**Issue by kevinoid** [rbuchberger/jekyll_picture_tag#133]
Thanks for maintaining this plugin, it looks great!

I just tried using this plugin and noticed that it does not appear to support file names which require URL encoding.  For example, with a file named 'wtf?.jpg' using `{% picture wtf%3F.jpg %}` results in:

    Liquid Exception: Jekyll Picture Tag could not find /tmp/wtf%3F.jpg. in index.html

while `{% picture wtf?.jpg %}` generates:

```html
<img src="/generated/wtf?-800by600-357a27.jpg" srcset="/generated/wtf?-400by300-357a27.jpg 400w, /generated/wtf?-600by450-357a27.jpg 600w, /generated/wtf?-800by600-357a27.jpg 800w, /generated/wtf?-1000by750-357a27.jpg 1000w">
```

which refers to the file `wtf` with a query string rather than the generated files.

I can see a few potential solutions:

1.  Treat `(source image)` in the liquid markup as URL-encoded and decode for filesystem access.
2.  Treat `(source image)` in the liquid markup as non-encoded and URL-encode in generated HTML.

Option 2 has the down-side noted in #59 that the liquid parsing would have to be extended to handle whitespace in `(source image)`.  This could be done with optional quoting, escaping, or some other method.  For that reason, I'd suggest option 1.

Thoughts?  I would be willing to write a PR, but be aware that I don't write Ruby frequently, so it may not be idiomatic.

Thanks for considering,
Kevin

**Comment by rbuchberger** [comment]
You're right! For now, it uses the same string as both the URL and the path. I'll look into implementing this, but I am pretty busy with other projects now so it might be a minute before I can get to it.

**Comment by kevinoid** [comment]
Great!  Thanks for the update and for considering implementing it.

**Comment by rbuchberger** [comment]
Digging into this a little more --

The Ruby standard library provides an [easy method](https://ruby-doc.org/stdlib-2.6.3/libdoc/uri/rdoc/URI/Escape.html#method-i-escape) to URI encode an arbitrary string, so that part's no problem. 

I don't think asking people to input URI encoded strings as filenames is intuitive or user friendly; I'd rather teach the tag parser to handle character escaping. You'd give it `my\ image.jpg` and it would use `my image.jpg` as the filename and `my%20image.jpg` for the URI. 

That, or we could use quotes instead. You'd give it `'my image.jpg'` and get the same result. I think that's more intuitive than character escaping, I hate it when I have to put backslashes all over the place. 

I'll start messing around with regexes and see if I can come up with something that works well.

**Comment by kevinoid** [comment]
Sure.  Sounds good to me.  Thanks for looking into it!
