### ISSUE TITLE
`data_dir` configuration setting not respected

### ISSUE THREAD

**Issue by h-enk** [rbuchberger/jekyll_picture_tag#142]
The `data_dir` configuration setting is not respected. 

https://jekyllrb.com/docs/configuration/default/

**Comment by rbuchberger** [comment]
I just tested quickly and it appears it does work. JPT pulls its data from jekyll's 'data' hash, not from the file directly. Do you have any more information that I can use to reproduce it?

The 'preset not found' warning printed to the console is hardcoded to `_data/picture.yml`; it shouldn't be too hard to pull in the Jekyll setting so that's correct.

**Comment by h-enk** [comment]
You're right. It does work. My mistake: I see now that the `data_dir` is relative to `source`. Thanks for you quick reply!

**Comment by rbuchberger** [comment]
No worries! The misleading error message is a real problem, thanks for pointing it out!
