### ISSUE TITLE
Is it possible to cache picture ?

### ISSUE THREAD

**Issue by ImaCrea** [rbuchberger/jekyll_picture_tag#191]
Hi there,
I'm starting to use more and more your plugin, thanks a lot!

I was wondering : is there a way to skip regenerating all pictures for each build? This is very time and energy consuming to reprocess all images at each build.

Thanks!

**Comment by rbuchberger** [comment]
That should not be happening. There was a bug related to that which I thought I'd fixed a few weeks ago which had to do with multiple translations, but as I said I thought I'd fixed that!

 Can you give me more information? Maybe a link to the repository? Otherwise, your _config.yml, Gemfile, and Gemfile.lock files would be helpful.

**Comment by ImaCrea** [comment]
Oh? Feel free to have a look here: https://git.indie.host/indiehost/website :)

**Comment by rbuchberger** [comment]
Thanks! I cloned the master branch to test locally.

So when I rebuild your site, I get a bunch of image size warnings, which is basically complaining that the width in the preset is larget than the image itself. The first build took 30 seconds on my machine, but all builds after that take 3-4 seconds. Is this the same behavior you're getting, or are you seeing all images re-generated every time?  

Regarding the image size warnings, it appears that you have many smallish icon and graphic type image files, which the default preset may not be the best for. You should write a preset to fit that use case, possibly using a pixel ratio srcset instead of a width based srcset.

**Comment by ImaCrea** [comment]
wow amazing! Yes a few images are too small and I'm ok with them not being rendered. But, when you build it again, don't you have again images re-generated, even though no new images has been added ?

**Comment by ImaCrea** [comment]
You can check for example my latest commit and what happened when building it here: https://git.indie.host/indiehost/website/-/jobs/919 

Starting line 84 it says it's generating images but none of them are new at all. Warnings are also coming back for the same images.

**Comment by rbuchberger** [comment]
Nope; as I said the second and later builds are much faster than the first. Are you using `bundle exec`?

Your build service may not cache anything in between builds, or it may only do so if you configure it to. Are you using it for development builds? Personally I prefer to run a server locally (`bundle exec jekyll serve --livereload`) for that purpose.

**Comment by ImaCrea** [comment]
I'm not sure I'm following you here :/ It's another folk who takes care of setting the CI pipe on our Gitlab.
When working locally, I do ```bundle exec jekyll serve```. I'll try your suggestion, thanks.

Do you manage to see on our repo what's going and eventually leave us some suggestion to make it run faster please?

**Comment by rbuchberger** [comment]
Right, so when you build locally, the first time you start with an empty _site folder, and all images must be regenerated. Every time after that, the old site is still there and only the new and/or changed files need to be regenerated. 

When you build with CI, usually the service will spin up a brand new container for every build. Check your logs-- it clones the repository, runs bundle install, and then `bundle exec jekyll build`. This means that every build is like the first; it starts with an empty _site folder. You need to configure your CI to carry the old images over to the new build. I'm fairly sure it's possible, but I'm not all that smart on the subject. Maybe talk to your CI folks?

**Comment by ImaCrea** [comment]
Understood :) Thanks a lot for your help, I'll check that with them.

**Comment by rbuchberger** [comment]
No worries, let me know if you have any more trouble!

**Comment by ImaCrea** [comment]
Reading https://mherman.org/blog/deploying-jekyll-netlify-docker-gitlab-ci/ it looks likes it's working with the ```artifacts``` command in gitlab-ci config file. I'll check with them. Thank again for the help Robert :)
